### ISSUE TITLE
change DB to mongodb

### ISSUE THREAD

**Issue by chaspy** [kamoshare/favobase#10]

**Comment by kamontia** [comment]
docker-compose up で以下のエラー

Step 10/10 : COPY . $APP_ROOT
 ---> 09a51b9a0a25
Successfully built 09a51b9a0a25
Successfully tagged favobase_web:latest
WARNING: Image for service web was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `doCreating favobase_db_1  ... error
Creating favobase_db_1  ... 

**ERROR: for favobase_db_1  Cannot start service db: driver failed programming external connectivity on endpoint favobase_db_1 (42fad87bb0ac9dc89d388454fe37b5cd64e3e69c41106a89b64053c291ee73ce): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use**

**ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint favobase_db_1 (42fad87bb0ac9dc89d388454fe37b5cd64e3e69c41106a89b64053c291ee73ce): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use
ERROR: Encountered errors while bringing up the project.**


ローカル環境でWebRickとMongoDBのサービスが起動していたのが原因でした。
docker-compose.ymlのポートバインドのFrom:ToをFromとToを同じにしない方が良いのかなあと思ったり。

**Comment by chaspy** [comment]
https://github.com/kamoshare/favobase/pull/11

issueとPRを紐付けるのはどうしたらいいんだろうか。

なるべくデフォルトポートを使いたいので、ローカル環境でportがぶつからないように注意するようどこかに記載することにしてマージしませんか？

**Comment by chaspy** [comment]
mergeされたのでクローズします。
